=== ZoolYe/JavaBasicsEnhance/src/zool/java/basics/dom4j/shiporder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="zool.java.xmlSchema"
	elementFormDefault="qualified">
<!-- 
	1，将定义好的Schema绑定到命名空间上，targetNamespace
	2，指定下面元素哪些需要绑定到命名空间上，elementFormDefault    qualified全部 		unqualified子元素可选的
 -->
	<xs:element name="shiporder">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="orderperson" type="xs:string" />
				<xs:element name="shipto">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" />
							<xs:element name="address" type="xs:string" />
							<xs:element name="city" type="xs:string" />
							<xs:element name="country" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="item" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" type="xs:string" />
							<xs:element name="note" type="xs:string" minOccurs="0" />
							<xs:element name="quantity" type="xs:positiveInteger" />
							<xs:element name="price" type="xs:decimal" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="orderid" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

</xs:schema>

=== ZoolYe/JavaBasicsEnhance/src/zool/java/basics/dom4j/shiporder.xml
<?xml version="1.0" encoding="UTF-8"?>
<shiporder xmlns="zool.java.xmlSchema"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="zool.java.xmlSchema shiporder.xsd" orderid="111">
		
	<orderperson>abc</orderperson>
	<shipto>
		<name>张三</name>
		<address>朝阳</address>
		<city>北京</city>
		<country>中国</country>
	</shipto>
	<item>
		<title>你好，欢迎！</title>
		<note></note>
		<quantity>123</quantity>
		<price>78.25</price>
	</item>
</shiporder>
